- q: What is Butterfleye?
  a: Butterfleye is the smart camera with Active Eye Intelligence that lets you see and hear what’s happening in your home when you are away. It automatically captures pictures and videos throughout the day and uploads them to the Cloud, where they can then be accessed via a smartphone. When you are home, Butterfleye becomes your personal photographer capturing candid moments that might otherwise be missed.

- q: What is Active Eye Intelligence?
  a: Butterfleye’s Active Eye Intelligence features a learning algorithm and video analytics that actually allows the camera to learn behavior. It knows when people are home and when they are not. It recognizes when there is an important event happening that needs to be recorded and understands when it is time for the camera to shut down. Instead of recording an empty living room, the camera’s energy sensor detects humans and pets and turns on when a live being enters the room.

- q: Is Butterfleye a surveillance camera or is it multi-purpose?
  a: Multi-purpose. It can be used as a surveillance camera when you are away, allowing you to check in on your home, pets and loved ones via previously recorded videos or through live looks. Butterfleye can also be taken on the go to record and capture important events and memories.

- q: Is Butterfleye portable?
  a: Butterfleye is 100-percent cord free. This allows the camera to be set up anyplace, anywhere, anytime. It also features 12 hours of built-in memory so a wireless(Wifi) connection is not required.

- q: Do I need an Internet connection to use Butterfleye?
  a: For live-view, uploading videos and photos Butterfleye needs to connect to internet. However Butterfleye also has built-in storage (capable of storing 12hours of high quality video) This enables Butterfleye to still record and save events without the internet and uploads them upon next connection

- q: What are exact measurements of Butterfleye?
  a: 94mm x 76mm x 38mm.

- q: Does the camera record audio as well as video?
  a: The camera includes a built in microphone and speaker allowing for two-way communication during live monitoring.

- q: How do I access the videos?
  a: Butterfleye automatically uploads videos to the cloud where they can be accessed via a smartphone app.

- q: Does the Butterfleye app run on iOS and Android?
  a: Currently Butterfleye only runs on iOS. We plan to make it available on Android in the near future.

- q: Can I share my content on social media?
  a: Yes. The app allows users to create, view, edit and save photos and video clips, and share them on various social media sites.

- q: How is the quality of the video?
  a: The Butterfleye camera is Full-HD and has a wide-view angle 3MPixel lens with high performance in low light environment. The camera includes face detection and a proximity sensor, automatically zooming in on the object of interest and producing high-resolution pictures and 1920 x 1080 videos.

- q: Do I need a computer to setup?
  a: No. Butterfleye out of the box only needs its mobile app to setup.

- q: How does Butterfleye know when I am home and when I am away to automatically switch modes?
  a: Butterfleye is smart, it leverages Bluetooth Smart technology to track your smartphone and therefore knows when you are coming home and when you have left the house.

- q: How long does the battery last?
  a: With average use, the battery will last about 2 weeks.

- q: How am I notified when my battery is low?
  a: You can check status of your battery at anytime through our Smartphone app. In addition when battery reaches 25% charge and lower, it will send a notification

- q: Can I keep Butterfleye plugged in to wall-wart?
  a: Yes.

- q: How much will the Butterfleye camera cost?
  a: The Butterfleye camera will retail for $249. For you early adopters there is a very limited quantity that can be purchased for $199. Cloud video storage will be available for an additional monthly fee.

- q: How are you different from your competitors?
  a: "Below is quick table of our major differentiations with Passive cameras: \n1.Heat & Movement detect -> Knows if there is a fire or burglar in the house\n2.Human & face & object detect -> Knows you or your child or your dog\n3.Social Intelligence  -> It tells you when to share\n4.Portable & cordless -> move around the house easily or take it to the park with you"

- q: Do you Ship internationally?
  a: Yes. There will be additional shipping cost to the price of pre-order

- q: Does the price include VAT or other duties?
  a: No. You are responsible for all other taxes and duties

- q: What kind of warranty do you provide?
  a: We will provide a limited warranty. If the device is defective we will replace it. If you damage it or decide that you don’t want it after we’ve shipped it to you, we will not be able to replace the device or offer a refund.

- q: How can I be notified about new features?
  a: Please follow Butterfleye on Twitter (@butterfleyecam) or like us on Facebook for updates on new features.

- q: How can I get help or support?
  a: Please email us at help@butterfleye.co We currently only offer email support. Our support hours are 8am-5pm PT Monday-Friday

- q: How do I get in touch about potential partnerships?
  a: Please email us at info@butterfleye.co

- q: Why are you charging me immediately for my pre-order?
  a: Creating and manufacturing new devices is expensive. As a young company, being able to use the revenue from your pre-order to pay for things as we build them helps us reduce risk and helps ensure that we deliver the best possible product and customer service to you

- q: Why aren’t you collecting my shipping information when I order?
  a: To reduce confusion, we’ll get your shipping info once we are a little closer to shipping your Butterfleye
